### ISSUE TITLE
How to use qtjambi to create a project.

### ISSUE THREAD

**Issue by xiaoliuzi** [qtjambi/qtjambi#3]
Hello everyone, I am an Qt beginner. I want to use qt to write java.

I have installed Qt5.5.1  and Qt Creator 3.5.1 in my linux system.

I downloaded qtjambi-linux32-community-4.8.7.tar.gz and opened it.There are some file in the directory.

![qq 20151024165911](https://cloud.githubusercontent.com/assets/5894711/10709872/9d17d83c-7a70-11e5-89d5-7f7f46d3de38.jpg)

and depend on this link
https://github.com/qtjambi/qtjambi/blob/master/INSTALL.md

to run the example successfully
···
java -cp qtjambi-4.8.6.jar:qtjambi-examples-4.8.6.jar:build/qtjambi-native-linux64-gcc-4.8.6.jar \
com.trolltech.launcher.Launcher
···

But I don't know how to use qtjambi to write java code, such as:writing code, compile and run.

Please help me..

Thank you very much.

**Comment by jfcabral** [comment]
Hello xiaoliuzi
Using Qt Jambi you will be able usw Qt from Java, but keep in mind that Jambi doesn't support Qt 5.x yet...

Here are a couple of links to help you get started:
- http://qtjambi.org/users/screencasts
- https://doc.qt.io/archives/qtjambi-4.5.2_01/com/trolltech/qt/qtjambi-tutorial1.html
- http://zetcode.com/gui/qtjambi/
- http://qtjambi.org/doc/examples

P.S. If you would like to create a GUI using Qt Designer you shoud run the "designer.sh" script. With this software you'll be able to create windows, widgets, dialogs, etc, and save it as a JUI file. Then you can use "juic" (should be in the bin folder) to convert that .jui file into a Java Class!

If you have more questions feel free to pass in our IRC: #qtjambi at freenode!

**Comment by xiaoliuzi** [comment]
Thanks for your reply. I read the links.

I have changed qt to 4.8.6 .

I have joined the IRC.

After I download the qtjambi-linux32-community-4.8.7.tar.gz from 

https://qtjambi.org.

and then I get some *.jar files. But I don't know how to use these *.jar file to Create the "Hello, World!"

this link:http://qtjambi.org/users/screencasts is both for eclipse, not for Qt Creator.

I want to create a project like this below to write java code.

![qt](https://cloud.githubusercontent.com/assets/5894711/10719846/4d6058b2-7bcb-11e5-85b8-240d11c3234a.jpg)

Please help me, Thanks.

**Comment by MiguelGonzalez** [comment]
Hi xiaoliuzi,

I use Netbeans to programme in Java; you only need add the next two jars in the project: qtjambi-4.8.9.jar and qtjambi-native-linux64-gcc-4.8.7.jar for Linux (64 bits).

A quick example is:

``` java
package qtexample;

import com.trolltech.qt.core.QTextCodec;
import com.trolltech.qt.gui.QApplication;
import com.trolltech.qt.gui.QLabel;
import com.trolltech.qt.gui.QMainWindow;
import com.trolltech.qt.gui.QVBoxLayout;
import com.trolltech.qt.gui.QWidget;

public class QTExample {

    public static void main(String[] args) {
        QApplication.initialize(args);
        QTextCodec.setCodecForCStrings(QTextCodec.codecForName("UTF-8"));
        QTextCodec.setCodecForLocale(QTextCodec.codecForName("UTF-8"));

        QMainWindow mainWindow = new QMainWindow();

        mainWindow.setWindowTitle("Hello world");        
        mainWindow.setMinimumHeight(150);
        mainWindow.setMinimumWidth(300);
        mainWindow.setVisible(true);

        QVBoxLayout vBoxLayout = new QVBoxLayout();
        QWidget mainWidget = new QWidget();
        mainWidget.setLayout(vBoxLayout);

        mainWindow.setCentralWidget(mainWidget);

        QLabel labelWorld = new QLabel("Hello world"); 
        vBoxLayout.addWidget(labelWorld);

        QApplication.execStatic();
    }
}
```

The examples.sh programm is very useful to learn how use the library.

**Comment by xiaoliuzi** [comment]
@MiguelGonzalez Thank you very much, I have to use qtcreator to write java code.

**Comment by MiguelGonzalez** [comment]
Your welcome @xiaoliuzi 
i've never use QT Creator so i cant help with it sorry :(

Good luck!

**Comment by xiaoliuzi** [comment]
Thanks for everyone's help. I get the help from IRC.

My envirment:

OS：Ubuntu 1404 
architect: amd64

I also did not use Qt Creator to create window.

But I can run the Hello World to produce a window.

1.first  wirte the code below and save as "HelloWorld.java" in the Qtjambi directory.

/*\*  package com.trolltech.examples.tutorial; **/

import com.trolltech.qt.gui.*;

public class HelloWorld
{
    public static void main(String args[])
    {
        QApplication.initialize(args);

```
    QPushButton hello = new QPushButton("Hello World!");
    hello.resize(120, 40);
    hello.setWindowTitle("Hello World");
    hello.show();

    QApplication.exec();
}
```

}

2.run the command to compile the HelloWorld.java file

$ javac -cp qtjambi-4.8.7.jar HelloWorld.java

3.run the command below 

java -cp qtjambi-4.8.7.jar:qtjambi-examples-4.8.7.jar:qtjambi-native-linux64-gcc-4.8.7.jar com.trolltech.examples.tutorial.HelloWorld

Then show the window successfully.

![qq 20151026181501](https://cloud.githubusercontent.com/assets/5894711/10726419/9071ac68-7c0d-11e5-990b-9a2ac431e460.jpg)

Thanks.

**Comment by jfcabral** [comment]
I'm glad you got it working. As far as I know Qt Creator is an IDE to develop Qt based applications in C++, so you won't be able to use i with Java or Jambi. Still, if you would like to create windows, widgets, dialogs, etc, graphically, you can use Qt Designer to do that! 

![Qt Designer](http://doc.qt.io/qt-4.8/images/designer-screenshot.png)

To run it you just need to type this at the Qt Jambi folder:

``` bash
sh designer.sh
```

**Comment by xiaoliuzi** [comment]
Thank you very much. :)

Thanks this project a lot.
